### ISSUE TITLE
Cannot compile in Xcode 16

### ISSUE THREAD

**Issue by vincentneo** [karwa/swift-url#186]
<img width="325" alt="error message" src="https://github.com/karwa/swift-url/assets/23420208/ff3a5726-f7af-4264-9e87-2ce89e2edc4c">
<img width="778" alt="error line" src="https://github.com/karwa/swift-url/assets/23420208/3e6d088f-9df4-4ff4-b893-b3aa3962ab33">

Not sure why `UnsafeRawPointer` init would be ambiguous. Tried casting but didn't work, if I find a solution I will open a pull request.

**Comment by karwa** [comment]
I've released 0.4.2 which fixes the issue. You may need to update packages to their latest version in Xcode for it to use the new version.

<img width="642" alt="Screenshot 2024-07-01 at 08 43 23" src="https://github.com/karwa/swift-url/assets/5254025/a704d775-dcff-44b0-b280-41a48a191eb0">
